### ISSUE TITLE
Something happened after i installed the plugin，about IDA API？

### ISSUE THREAD

**Issue by edgarfy** [AntoineBlaud/TheCodexRebirth#8]
C:\Tools\XData\Reverse\DEBUG\IDA_Pro_v8.3\plugins\tenet_plugin.py: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "C:\Tools\XData\Reverse\DEBUG\IDA_Pro_v8.3\python\3\ida_idaapi.py", line 577, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Tools/XData/Reverse/DEBUG/IDA_Pro_v8.3/plugins/tenet_plugin.py", line 4, in <module>
    logger = start_logging()
             ^^^^^^^^^^^^^^^
  File "C:\Tools/XData/Reverse/DEBUG/IDA_Pro_v8.3/plugins\tenet\util\log.py", line 133, in start_logging
    log_dir = get_log_dir()
              ^^^^^^^^^^^^^
  File "C:\Tools/XData/Reverse/DEBUG/IDA_Pro_v8.3_Portable/plugins\tenet\util\log.py", line 32, in get_log_dir
    log_directory = os.path.join(disassembler.get_root_filename_dir(), "tenet_logs")
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Tools/XData/Reverse/DEBUG/IDA_Pro_v8.3_Portable/plugins\tenet\integration\api\ida_api.py", line 194, in get_root_filename_dir
    return os.path.dirname(self.get_root_filename())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 251, in dirname
  File "<frozen ntpath>", line 213, in split
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by AntoineBlaud** [comment]
Hello @edgarfy 

This error occurs when IDA is opened without an input file. Tenet logs are saved in the same directory as the loaded binary; if no binary is loaded, the IDA API returns None. In the next version, I will implement error handling to provide a clearer message when this happens. Additionally, I'm currently developing a new tracer, which I plan to release soon.

Thank you for your feedback!
