### ISSUE TITLE
The runtime error "AttributeError: 'NoneType' object has no attribute 'analysis'"

### ISSUE THREAD

**Issue by ll00llgoog** [AntoineBlaud/TheCodexRebirth#9]
Traceback (most recent call last):
  File "H:\xxxx/IDA_Pro_8.3/IDA_Pro_8.3/plugins\tenet\integration\ida_integration.py", line 559, in activate
    self.action_function(IDA_GLOBAL_CTX)
  File "H:\xxxx/IDA_Pro_8.3/IDA_Pro_8.3/plugins\tenet\core.py", line 233, in _interactive_prev_execution
    pctx.interactive_prev_execution()
  File "H:\xxxx/IDA_Pro_8.3/IDA_Pro_8.3/plugins\tenet\context.py", line 388, in interactive_prev_execution
    rebased_address = self.reader.analysis.rebase_pointer(address)
                      ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'analysis'
Traceback (most recent call last):
  File "H:\xxxx/IDA_Pro_8.3/IDA_Pro_8.3/plugins\tenet\integration\ida_integration.py", line 559, in activate
    self.action_function(IDA_GLOBAL_CTX)
  File "H:\xxxx/IDA_Pro_8.3/IDA_Pro_8.3/plugins\tenet\core.py", line 229, in _interactive_next_execution
    pctx.interactive_next_execution()
  File "H:\xxxx/IDA_Pro_8.3/IDA_Pro_8.3/plugins\tenet\context.py", line 376, in interactive_next_execution
    rebased_address = self.reader.analysis.rebase_pointer(address)
                      ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'analysis'

![image](https://github.com/user-attachments/assets/8b84b853-d3d6-45e9-ae83-2897ac4c728f)
The issue occurs when I use Shift+P and Shift+N.

What should I do to fix this error? 
PS：If you can help me understand the role of this variable, I can try to fix it.

**Comment by AntoineBlaud** [comment]
Hello @ll00llgoog,

I’m not sure which version you’re using, but it’s not the latest one. Please pull the latest version from the main branch, synchronize the tenet directory inside the plugin directory, and let me know if self.reader is still causing issues. 

And I think it’s obvious, but the trace file must be opened before using previous and next execution shortcuts.

**Comment by electricalArt** [comment]
I have the same issue ("AttributeError: 'NoneType' object has no attribute 'analysis') with the latest version of the plugin.

> the trace file must be opened before using previous and next execution shortcuts.
How it should be opened? It would be appreciated to have a step-by-step guide for the plugin.

**Comment by AntoineBlaud** [comment]
Hi @electricalArt,

I tested a fresh installation  and noticed some problems specifically on Windows, particularly with line_profile and capstone. It seems your installation might not be complete, which could explain why the options menu is missing.

To enable the options menu, you need to right-click (open the context menu) while hovering over the disassembly view. Below, I've included a screenshot for reference.


![Image](https://github.com/user-attachments/assets/f5ef1543-dae2-47a0-98a7-e94c06e8f9c4)
